//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsTracker.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public int EventId { get; set; }
        public string Message { get; set; }
        public System.DateTime EventDate { get; set; }
        public string DeviceId { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
