//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsTracker.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int TrackId { get; set; }
        public int MarkerId { get; set; }
        public int UserId { get; set; }
    
        public virtual Marker Marker { get; set; }
        public virtual User User { get; set; }
    }
}
