//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsTracker.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public int ZoneId { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public double Radius { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
    }
}
